version: '3'

services:
  app:
    image: adapt-client-docker-dev
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles