version: '3'

services:
  app:
    image: adapt-client-docker-dev
    build: .
    ports:
      - 3010:3000    
    volumes:
      - ./app:/app/app
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
      - .env.local:/app/.env.local
