version: '3'

services:
  app:
    image: adapt-server-docker-dev
    build: .
    ports:
      - 1337:1337
    volumes:
      - ./src:/parse/src
      - ./cloud:/parse/cloud
      - ./scripts:/parse/scripts
